
List<Map<String, dynamic>> restaurants = [

  {
    "image": "assets/restaurant2.jpg",
    "name": "Burger Haven",
    "address": "456 Oak St",
    "menu": [
      {"image": "assets/sushi.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/burger.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/checolat.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer1.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/offer2.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer3.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/offer4.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/pizza.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/shawarma.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/strobery.jpg", "name": "iced chocolat", "price": "\$7.99"},
    ],
  },
  {
    "image": "assets/restaurant3.jpg",
    "name": "Sushi World",
    "address": "789 Pine St",
    "menu": [
      {"image": "assets/sushi.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/burger.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/checolat.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer1.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/offer2.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer3.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/offer4.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/pizza.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/shawarma.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/strobery.jpg", "name": "iced chocolat", "price": "\$7.99"},
    ],
  },
  {
    "image": "assets/restaurant4.jpg",
    "name": "Taco Town",
    "address": "101 Maple St",
    "menu": [
      {"image": "assets/sushi.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/burger.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/checolat.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer1.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/offer2.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer3.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/offer4.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/pizza.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/shawarma.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/strobery.jpg", "name": "iced chocolat", "price": "\$7.99"},
    ],
  },
  {
    "image": "assets/restaurant1.jpg",
    "name": "Pizza Palace",
    "address": "123 Main St",
    "menu": [
      {"image": "assets/sushi.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/burger.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/checolat.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer1.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/offer2.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer3.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/offer4.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/pizza.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/shawarma.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/strobery.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
    ],
  },
  {
    "image": "assets/restaurant5.jpg",
    "name": "Burger Haven",
    "address": "456 Oak St",
    "menu": [
      {"image": "assets/sushi.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/burger.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/checolat.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer1.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/offer2.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer3.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/offer4.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/pizza.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/shawarma.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/strobery.jpg", "name": "iced chocolat", "price": "\$7.99"},
    ],
  },
  {
    "image": "assets/restaurant6.jpg",
    "name": "Sushi World",
    "address": "789 Pine St",
    "menu": [
      {"image": "assets/sushi.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/burger.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/checolat.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer1.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/offer2.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer3.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/offer4.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/pizza.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/shawarma.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/strobery.jpg", "name": "iced chocolat", "price": "\$7.99"},
    ],
  },
  {
    "image": "assets/restaurant4.jpg",
    "name": "Taco Town",
    "address": "101 Maple St",
    "menu": [
      {"image": "assets/sushi.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/burger.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/checolat.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer1.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/offer2.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer3.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/offer4.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/pizza.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/shawarma.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/strobery.jpg", "name": "iced chocolat", "price": "\$7.99"},
    ],
  },
  {
    "image": "assets/restaurant1.jpg",
    "name": "Pizza Palace",
    "address": "123 Main St",
    "menu": [
      {"image": "assets/sushi.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/burger.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/checolat.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer1.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/offer2.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer3.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/offer4.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/pizza.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/shawarma.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/strobery.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
    ],
  },
  {
    "image": "assets/restaurant2.jpg",
    "name": "Burger Haven",
    "address": "456 Oak St",
    "menu": [
      {"image": "assets/sushi.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/burger.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/checolat.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer1.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/offer2.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer3.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/offer4.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/pizza.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/shawarma.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/strobery.jpg", "name": "iced chocolat", "price": "\$7.99"},
    ],
  },
  {
    "image": "assets/restaurant5.jpg",
    "name": "Sushi World",
    "address": "789 Pine St",
    "menu": [
      {"image": "assets/sushi.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/burger.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/checolat.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer1.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/offer2.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer3.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/offer4.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/pizza.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/shawarma.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/strobery.jpg", "name": "iced chocolat", "price": "\$7.99"},
    ],
  },
  {
    "image": "assets/restaurant6.jpg",
    "name": "Taco Town",
    "address": "101 Maple St",
    "menu": [
      {"image": "assets/sushi.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/burger.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/checolat.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer1.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/offer2.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer3.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/offer4.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/pizza.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/shawarma.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/strobery.jpg", "name": "iced chocolat", "price": "\$7.99"},
    ],
  },
  {
    "image": "assets/restaurant1.jpg",
    "name": "Pizza Palace",
    "address": "123 Main St",
    "menu": [
      {"image": "assets/sushi.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/burger.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/checolat.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer1.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/offer2.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer3.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/offer4.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/pizza.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/shawarma.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/strobery.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
    ],
  },
  {
    "image": "assets/restaurant2.jpg",
    "name": "Burger Haven",
    "address": "456 Oak St",
    "menu": [
      {"image": "assets/sushi.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/burger.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/checolat.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer1.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/offer2.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer3.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/offer4.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/pizza.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/shawarma.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/strobery.jpg", "name": "iced chocolat", "price": "\$7.99"},
    ],
  },
  {
    "image": "assets/restaurant3.jpg",
    "name": "Sushi World",
    "address": "789 Pine St",
    "menu": [
      {"image": "assets/sushi.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/burger.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/checolat.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer1.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/offer2.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer3.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/offer4.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/pizza.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/shawarma.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/strobery.jpg", "name": "iced chocolat", "price": "\$7.99"},
    ],
  },
  {
    "image": "assets/restaurant4.jpg",
    "name": "Taco Town",
    "address": "101 Maple St",
    "menu": [
      {"image": "assets/sushi.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/burger.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/checolat.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer1.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/offer2.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer3.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/offer4.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/pizza.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/shawarma.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/strobery.jpg", "name": "iced chocolat", "price": "\$7.99"},
    ],
  },
  {
    "image": "assets/restaurant1.jpg",
    "name": "Pizza Palace",
    "address": "123 Main St",
    "menu": [
      {"image": "assets/sushi.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/burger.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/checolat.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer1.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/offer2.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer3.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/offer4.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/pizza.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/shawarma.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/strobery.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
    ],
  },
  {
    "image": "assets/restaurant6.jpg",
    "name": "Pizza Palace",
    "address": "123 Main St",
    "menu": [
      {"image": "assets/sushi.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/burger.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/checolat.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer1.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/offer2.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer3.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/offer4.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/pizza.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/shawarma.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/strobery.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
    ],
  },
  {
    "image": "assets/restaurant5.jpg",
    "name": "Pizza Palace",
    "address": "123 Main St",
    "menu": [
      {"image": "assets/sushi.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/burger.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/checolat.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer1.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/offer2.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/offer3.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/offer4.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/pizza.jpg", "name": "Spicy Tuna Roll", "price": "\$7.99"},
      {"image": "assets/shawarma.jpg", "name": "Beef burger", "price": "\$3.99"},
      {"image": "assets/strobery.jpg", "name": "iced chocolat", "price": "\$7.99"},
      {"image": "assets/fruit.jpg", "name": "Beef burger", "price": "\$3.99"},
    ],
  },
];
