// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFJqQ-NrMAmwQzvw-9tjl3M5-IVNV2TTc',
    appId: '1:923151957337:web:61ab34f0ca63cd69cb2048',
    messagingSenderId: '923151957337',
    projectId: 'delivery-app-414b7',
    authDomain: 'delivery-app-414b7.firebaseapp.com',
    storageBucket: 'delivery-app-414b7.appspot.com',
    measurementId: 'G-FHD3EKT8LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARZLj36HE8kuPdAEX6V_MV-z23QHHB0ho',
    appId: '1:923151957337:android:0b1e1d4a8e953f9fcb2048',
    messagingSenderId: '923151957337',
    projectId: 'delivery-app-414b7',
    storageBucket: 'delivery-app-414b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEr3x6LAq4QY2RQXzo4OlL6KOncoxK_yg',
    appId: '1:923151957337:ios:0e9a674a1c89f75ecb2048',
    messagingSenderId: '923151957337',
    projectId: 'delivery-app-414b7',
    storageBucket: 'delivery-app-414b7.appspot.com',
    iosBundleId: 'com.example.deliveryApp',
  );
}
